apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ___namespace___
  name: orders
  labels:
    app: orders-api
    version: ___deploymentVersion___
spec:
  replicas: ___replicas___
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
      - name: orders-api
        image: ___dockerImage___
        ports:
        - containerPort: 80
        env:
        - name: DEPLOYMENT_VERSION
          value: ___deploymentVersion___
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: ___namespace___
  name: orders-api
  labels:
    app: orders-api
spec:
  ports:
  - port: 80
    protocol: TCP
  type: NodePort
  selector:
    app: orders-api